# Generated by Django 5.0.6 on 2025-02-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattingFirstPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('batting_first', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=100)),
                ('present_score', models.IntegerField()),
                ('wickets_left', models.IntegerField()),
                ('balls_remaining', models.IntegerField()),
                ('predict_target', models.IntegerField()),
            ],
        ),
    ]
