# Generated by Django 5.0.6 on 2025-02-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_battingfirstpredict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict_winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('wickets1', models.IntegerField()),
                ('wickets2', models.IntegerField()),
                ('balls_left1', models.IntegerField()),
                ('balls_left2', models.IntegerField()),
                ('winner', models.CharField(max_length=100)),
            ],
        ),
    ]
