# Generated by Django 5.0.6 on 2025-02-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_predict_winner'),
    ]

    operations = [
    ]
