# Generated by Django 5.0.6 on 2025-02-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_player_o_r'),
    ]

    operations = [
    ]
