# Generated by Django 5.0.6 on 2025-02-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20250225_0951'),
    ]

    operations = [
    ]
