# Generated by Django 5.0.6 on 2025-02-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20250225_1848'),
    ]

    operations = [
    ]
