# Generated by Django 5.0.6 on 2025-02-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20250225_1851'),
    ]

    operations = [
    ]
