# Generated by Django 5.0.6 on 2025-02-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20250225_1855'),
    ]

    operations = [
    ]
