# Generated by Django 5.0.6 on 2025-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20250225_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict_winner',
            old_name='balls_left1',
            new_name='balls_rem',
        ),
        migrations.RenameField(
            model_name='predict_winner',
            old_name='balls_left2',
            new_name='pre_score',
        ),
        migrations.RenameField(
            model_name='predict_winner',
            old_name='score1',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='predict_winner',
            old_name='score2',
            new_name='wic_left',
        ),
        migrations.RemoveField(
            model_name='predict_winner',
            name='wickets1',
        ),
        migrations.RemoveField(
            model_name='predict_winner',
            name='wickets2',
        ),
        migrations.AddField(
            model_name='predict_winner',
            name='bat_first',
            field=models.CharField(default='csk', max_length=30),
        ),
    ]
