# Generated by Django 5.0.6 on 2025-02-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_balls_left1_predict_winner_balls_rem_and_more'),
    ]

    operations = [
    ]
