# Generated by Django 5.0.6 on 2025-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20250225_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict_win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('pre_score', models.IntegerField()),
                ('bat_first', models.CharField(default='csk', max_length=30)),
                ('wic_left', models.IntegerField()),
                ('balls_rem', models.IntegerField()),
                ('target', models.IntegerField()),
                ('winner', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Predict_winner',
        ),
    ]
