# Generated by Django 5.0.6 on 2025-02-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_predict_win_delete_predict_winner'),
    ]

    operations = [
    ]
