# Generated by Django 5.0.6 on 2025-02-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20250226_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipl_2025_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('predicted_winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
