# Generated by Django 5.0.6 on 2025-02-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_ipl_2025_matches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ipl_2025_matches',
            new_name='Ipl_matches',
        ),
    ]
