# Generated by Django 5.0.6 on 2025-02-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_ipl_2025_matches_ipl_matches'),
    ]

    operations = [
    ]
