# Generated by Django 5.0.6 on 2025-02-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20250227_1815'),
    ]

    operations = [
    ]
