# Generated by Django 5.0.6 on 2025-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20250227_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict_win',
            name='team1_runs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predict_win',
            name='team2_runs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
