# Generated by Django 5.0.6 on 2025-08-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_predict_win_team1_runs_predict_win_team2_runs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict_win',
            old_name='team1_runs',
            new_name='team1_run',
        ),
        migrations.RenameField(
            model_name='predict_win',
            old_name='team2_runs',
            new_name='team2_run',
        ),
    ]
