# Generated by Django 5.0.6 on 2025-08-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_rename_team1_runs_predict_win_team1_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict_win',
            name='team1_run',
        ),
        migrations.RemoveField(
            model_name='predict_win',
            name='team2_run',
        ),
        migrations.AddField(
            model_name='predict_win',
            name='t1_runs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predict_win',
            name='t2_runs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
