# Generated by Django 5.0.6 on 2025-08-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_predict_win_team1_run_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict_win',
            old_name='t1_runs',
            new_name='team1_runs',
        ),
        migrations.RenameField(
            model_name='predict_win',
            old_name='t2_runs',
            new_name='team2_runs',
        ),
    ]
