# Generated by Django 5.0.6 on 2025-08-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_rename_t1_runs_predict_win_team1_runs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('team1', models.CharField(max_length=20)),
                ('team2', models.CharField(max_length=20)),
                ('winner', models.CharField(max_length=20)),
                ('is_selected', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='predict_win',
            name='team1_runs',
        ),
        migrations.RemoveField(
            model_name='predict_win',
            name='team2_runs',
        ),
    ]
