# Generated by Django 5.0.6 on 2025-08-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_matchresult_remove_predict_win_team1_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='venue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
