# Generated by Django 5.0.6 on 2025-08-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_matchresult_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('team1', models.CharField(max_length=20)),
                ('team2', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=20)),
                ('is_selected', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
