# Generated by Django 5.0.6 on 2025-08-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_matchres_delete_matchresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchRes',
            new_name='MatchResult',
        ),
    ]
