# Generated by Django 5.0.6 on 2025-08-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_rename_matchres_matchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('pitch_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OverallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=100)),
                ('pitch_type', models.CharField(max_length=50)),
                ('predicted_winner', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
