# Generated by Django 5.0.6 on 2025-08-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_groundinfo_overallresult_delete_matchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder')], max_length=20)),
                ('strike_rate', models.FloatField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('wickets', models.IntegerField(blank=True, null=True)),
                ('overs', models.FloatField(blank=True, null=True)),
                ('venue', models.CharField(max_length=100)),
                ('pitch_type', models.CharField(max_length=50)),
                ('catches', models.IntegerField(default=0)),
            ],
        ),
    ]
