# Generated by Django 5.0.6 on 2025-08-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_playerpredict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerpredict',
            old_name='catches',
            new_name='economy',
        ),
    ]
