# Generated by Django 5.0.6 on 2025-08-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_rename_catches_playerpredict_economy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpredict',
            name='role',
        ),
    ]
