# Generated by Django 5.0.6 on 2025-02-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20250222_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='O_R',
            field=models.FloatField(default=0.0),
        ),
    ]
